name: flutter_chatbook
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 0.0.2-alpha
issue_tracker: https://github.com/Yogesh-Dubey-Ayesavi/flutter_chatbook/issues
repository: https://github.com/Yogesh-Dubey-Ayesavi/flutter_chatbook
publish_to : None

platforms:
  android:
  ios:
  web:


environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: 'flutter'
  grouped_list: ^5.1.2
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.7
  any_link_preview: ^3.0.1
  flutter_parsed_text: ^2.2.1
  swipeable_tile: ^2.0.0+3
  scroll_to_index: ^3.0.1

  vibration: ^1.7.6
  path: ^1.8.2
  intl: ^0.19.0
  uuid: ^4.0.1
  parsed_readmore: ^0.0.6
  flutter_svg: ^2.0.7
  message_models:
    path: ../message_models


dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  lints: ^4.0.0

flutter:

  assets:
    - packages/flutter_chatbook/assets/graphics/reply.svg
    - packages/flutter_chatbook/assets/graphics/delete_icon.svg
    - packages/flutter_chatbook/assets/graphics/edit_icon.svg 
    - packages/flutter_chatbook/assets/graphics/mail_arrow.svg
    - packages/flutter_chatbook/assets/graphics/unread_icon.svg
    - packages/flutter_chatbook/assets/graphics/reply.svg
    - packages/flutter_chatbook/assets/graphics/people.svg
    - packages/flutter_chatbook/assets/graphics/location.svg 
    - packages/flutter_chatbook/assets/graphics/media.svg
    - packages/flutter_chatbook/assets/graphics/money.svg
    - packages/flutter_chatbook/assets/graphics/shift.svg
    - packages/flutter_chatbook/assets/graphics/clock.svg
    - packages/flutter_chatbook/assets/graphics/shift_name_icon.svg
    - packages/flutter_chatbook/assets/graphics/add_icon.svg
    - packages/flutter_chatbook/assets/graphics/send_button.svg

    
    
    





