name: message_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.1.0
  # path: ^1.8.0

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
