// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdaha-oxmc1AKmRuIAM10W3NT3ig5lkBQ',
    appId: '1:955105553521:web:1882735535ce41aa5fbfd0',
    messagingSenderId: '955105553521',
    projectId: 'dev-assisto',
    authDomain: 'dev-assisto.firebaseapp.com',
    storageBucket: 'dev-assisto.appspot.com',
    measurementId: 'G-5TL89DXGD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3b0l5TZQZBu7DSt1XFqO-xYhL-FNy1k',
    appId: '1:955105553521:android:6914dd603b3a7dc95fbfd0',
    messagingSenderId: '955105553521',
    projectId: 'dev-assisto',
    storageBucket: 'dev-assisto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG3bIlaQmSXLBLBVjD_VTunpaZ9Dc_nxs',
    appId: '1:955105553521:ios:c466c4f4b77e31d85fbfd0',
    messagingSenderId: '955105553521',
    projectId: 'dev-assisto',
    storageBucket: 'dev-assisto.appspot.com',
    iosBundleId: 'in.ayesavi.assisto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG3bIlaQmSXLBLBVjD_VTunpaZ9Dc_nxs',
    appId: '1:955105553521:ios:65f69946bfc861df5fbfd0',
    messagingSenderId: '955105553521',
    projectId: 'dev-assisto',
    storageBucket: 'dev-assisto.appspot.com',
    iosBundleId: 'com.example.assisto.RunnerTests',
  );
}
